
montecarlo: montecarlo.cpp init_states.cpp choice_functions.cpp agent.cpp init_states.h choice_functions.h agent.h
	g++ -std=c++11 -g -o montecarlo init_states.cpp choice_functions.cpp agent.cpp montecarlo.cpp

simpleAlg: simpleAlg.cpp init_states.cpp choice_functions.cpp agent.cpp init_states.h choice_functions.h agent.h
	g++ -std=c++11 -g -o simpleAlg init_states.cpp choice_functions.cpp agent.cpp simpleAlg.cpp

